name: learning_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  convex_bottom_bar: ^3.2.0
  lottie: ^2.7.0
  line_awesome_flutter: ^2.0.0
  clay_containers: ^0.3.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  http: ^1.1.2
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.2
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  dio: ^5.8.0+1
  dio_cache_interceptor_isar_store: ^1.0.1
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  google_nav_bar: ^5.0.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/c_sharp.png
    - assets/images/react_native.png
    - assets/images/Flutter.png
    - assets/images/Python.png
    - assets/images/banner_img.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
